- name: restart st2
  become: yes
  service:
    name: "{{ item }}"
    state: restarted
    sleep: 1
  with_items: "{{ st2_services }}"
  failed_when: False

- name: reload st2
  become: yes
  command: st2ctl reload --register-all

- name: restart st2api
  become: yes
  service:
    name: st2api
    state: restarted
    sleep: 1

- name: restart st2stream
  become: yes
  service:
    name: st2stream
    state: restarted
    sleep: 1
