---
- name: Install libffi-devel on EL6
  become: yes
  package:
    name: http://rpmfind.net/linux/centos/6/os/x86_64/Packages/libffi-devel-3.0.5-3.2.el6.x86_64.rpm
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- name: Install latest st2 package
  become: yes
  package:
    name: st2
    state: latest
  when: st2_version == "latest"
  notify:
    - restart st2
  tags: skip_ansible_lint

- name: Install pinned st2 package
  become: yes
  package:
    name: st2={{ st2_version }}-{{ st2_revision }}
    state: present
  when: st2_version != "latest"
  notify:
    - restart st2

- name: Create and configure StackStorm system user
  include: user.yml

- name: Configure StackStorm authentication
  include: config_auth.yml
  when: st2_auth_enable

- name: Ensure StackStorm services are enabled and running
  become: yes
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ st2_services }}"
  failed_when: False

- shell: cat /var/log/st2/st2api*
  register: result

- debug:
    msg: "{{ result }}"

- fail:
    msg: "[DEBUG!] Stop here"
